default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: llamaapp_development

test:
  <<: *default
  database: llamaapp_test

production:
  <<: *default
  database: llamaapp_production
  username: llamaapp
  password: <%= ENV['DATABASE_PASSWORD'] %>
